# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/buildRpmWizard.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Wizard(object):
    def setupUi(self, Wizard):
        Wizard.setObjectName("Wizard")
        Wizard.resize(717, 547)
        icon = QtGui.QIcon.fromTheme("list-add")
        Wizard.setWindowIcon(icon)
        Wizard.setWizardStyle(QtWidgets.QWizard.ModernStyle)
        self.wizardPage = QtWidgets.QWizardPage()
        self.wizardPage.setObjectName("wizardPage")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.wizardPage)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_2 = QtWidgets.QLabel(self.wizardPage)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.wizardPage)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_2.addWidget(self.lineEdit, 0, 1, 1, 4)
        self.label_3 = QtWidgets.QLabel(self.wizardPage)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 1, 0, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.wizardPage)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_2.addWidget(self.lineEdit_2, 1, 1, 1, 4)
        self.label_4 = QtWidgets.QLabel(self.wizardPage)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 2, 0, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.wizardPage)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout_2.addWidget(self.lineEdit_3, 2, 1, 1, 4)
        self.label_5 = QtWidgets.QLabel(self.wizardPage)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 3, 0, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.wizardPage)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout_2.addWidget(self.lineEdit_4, 3, 1, 1, 4)
        self.label_6 = QtWidgets.QLabel(self.wizardPage)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 4, 0, 1, 1)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.wizardPage)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout_2.addWidget(self.lineEdit_5, 4, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(140, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 4, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(140, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 4, 3, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(140, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 4, 4, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.wizardPage)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 5, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.wizardPage)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout_2.addWidget(self.comboBox, 5, 1, 1, 4)
        self.groupBox = QtWidgets.QGroupBox(self.wizardPage)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.groupBox)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.gridLayout_3.addWidget(self.plainTextEdit, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 6, 0, 1, 5)
        Wizard.addPage(self.wizardPage)
        self.wizardPage_2 = QtWidgets.QWizardPage()
        self.wizardPage_2.setObjectName("wizardPage_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.wizardPage_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_8 = QtWidgets.QLabel(self.wizardPage_2)
        self.label_8.setFrameShape(QtWidgets.QFrame.Box)
        self.label_8.setObjectName("label_8")
        self.gridLayout_4.addWidget(self.label_8, 0, 0, 1, 1)
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(self.wizardPage_2)
        self.plainTextEdit_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.gridLayout_4.addWidget(self.plainTextEdit_2, 1, 0, 1, 1)
        Wizard.addPage(self.wizardPage_2)
        self.wizardPage_3 = QtWidgets.QWizardPage()
        self.wizardPage_3.setObjectName("wizardPage_3")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.wizardPage_3)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.tabWidget = QtWidgets.QTabWidget(self.wizardPage_3)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.plainTextEdit_3 = QtWidgets.QPlainTextEdit(self.tab)
        self.plainTextEdit_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.plainTextEdit_3.setObjectName("plainTextEdit_3")
        self.gridLayout_5.addWidget(self.plainTextEdit_3, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.plainTextEdit_4 = QtWidgets.QPlainTextEdit(self.tab_2)
        self.plainTextEdit_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.plainTextEdit_4.setObjectName("plainTextEdit_4")
        self.gridLayout_7.addWidget(self.plainTextEdit_4, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.plainTextEdit_5 = QtWidgets.QPlainTextEdit(self.tab_3)
        self.plainTextEdit_5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.plainTextEdit_5.setObjectName("plainTextEdit_5")
        self.gridLayout_8.addWidget(self.plainTextEdit_5, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.plainTextEdit_6 = QtWidgets.QPlainTextEdit(self.tab_4)
        self.plainTextEdit_6.setFrameShadow(QtWidgets.QFrame.Plain)
        self.plainTextEdit_6.setObjectName("plainTextEdit_6")
        self.gridLayout_9.addWidget(self.plainTextEdit_6, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_4, "")
        self.gridLayout_6.addWidget(self.tabWidget, 0, 0, 1, 1)
        Wizard.addPage(self.wizardPage_3)
        self.wizardPage2 = QtWidgets.QWizardPage()
        self.wizardPage2.setObjectName("wizardPage2")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.wizardPage2)
        self.gridLayout_11.setObjectName("gridLayout_11")
        spacerItem3 = QtWidgets.QSpacerItem(350, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem3, 1, 1, 1, 1)
        self.commandLinkButton = QtWidgets.QCommandLinkButton(self.wizardPage2)
        self.commandLinkButton.setObjectName("commandLinkButton")
        self.gridLayout_11.addWidget(self.commandLinkButton, 1, 2, 1, 1)
        self.commandLinkButton_2 = QtWidgets.QCommandLinkButton(self.wizardPage2)
        icon = QtGui.QIcon.fromTheme("list-remove")
        self.commandLinkButton_2.setIcon(icon)
        self.commandLinkButton_2.setObjectName("commandLinkButton_2")
        self.gridLayout_11.addWidget(self.commandLinkButton_2, 1, 0, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(self.wizardPage2)
        self.tableWidget.setFrameShape(QtWidgets.QFrame.Panel)
        self.tableWidget.setFrameShadow(QtWidgets.QFrame.Plain)
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.gridLayout_11.addWidget(self.tableWidget, 0, 0, 1, 3)
        Wizard.addPage(self.wizardPage2)
        self.wizardPage_4 = QtWidgets.QWizardPage()
        self.wizardPage_4.setObjectName("wizardPage_4")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.wizardPage_4)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.groupBox_6 = QtWidgets.QGroupBox(self.wizardPage_4)
        self.groupBox_6.setCheckable(True)
        self.groupBox_6.setChecked(False)
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.label_11 = QtWidgets.QLabel(self.groupBox_6)
        self.label_11.setObjectName("label_11")
        self.gridLayout_17.addWidget(self.label_11, 0, 0, 1, 1)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.gridLayout_17.addWidget(self.lineEdit_8, 0, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox_6)
        self.label_13.setObjectName("label_13")
        self.gridLayout_17.addWidget(self.label_13, 1, 0, 1, 1)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.gridLayout_17.addWidget(self.lineEdit_9, 1, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.groupBox_6)
        self.label_14.setObjectName("label_14")
        self.gridLayout_17.addWidget(self.label_14, 2, 0, 1, 1)
        self.lineEdit_10 = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.gridLayout_17.addWidget(self.lineEdit_10, 2, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.groupBox_6)
        self.label_15.setObjectName("label_15")
        self.gridLayout_17.addWidget(self.label_15, 3, 0, 1, 1)
        self.lineEdit_11 = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.gridLayout_17.addWidget(self.lineEdit_11, 3, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(58, 248, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_17.addItem(spacerItem4, 4, 1, 1, 1)
        self.gridLayout_18.addWidget(self.groupBox_6, 0, 0, 1, 1)
        Wizard.addPage(self.wizardPage_4)
        self.wizardPage_5 = QtWidgets.QWizardPage()
        self.wizardPage_5.setObjectName("wizardPage_5")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.wizardPage_5)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.scrollArea = QtWidgets.QScrollArea(self.wizardPage_5)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 268, 565))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.label_12 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_12.setObjectName("label_12")
        self.gridLayout_16.addWidget(self.label_12, 0, 0, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.gridLayout_16.addWidget(self.comboBox_2, 0, 1, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_3.setCheckable(True)
        self.groupBox_3.setChecked(False)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.gridLayout_13.addWidget(self.lineEdit_12, 0, 0, 1, 2)
        self.listWidget = QtWidgets.QListWidget(self.groupBox_3)
        self.listWidget.setObjectName("listWidget")
        self.gridLayout_13.addWidget(self.listWidget, 1, 0, 3, 1)
        self.pushButton = QtWidgets.QPushButton(self.groupBox_3)
        icon = QtGui.QIcon.fromTheme("list-add")
        self.pushButton.setIcon(icon)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_13.addWidget(self.pushButton, 1, 1, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_3)
        icon = QtGui.QIcon.fromTheme("list-remove")
        self.pushButton_2.setIcon(icon)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_13.addWidget(self.pushButton_2, 2, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_13.addItem(spacerItem5, 3, 1, 1, 1)
        self.gridLayout_16.addWidget(self.groupBox_3, 1, 0, 1, 3)
        self.groupBox_4 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_4.setCheckable(True)
        self.groupBox_4.setChecked(False)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.lineEdit_13 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.gridLayout_14.addWidget(self.lineEdit_13, 0, 0, 1, 2)
        self.listWidget_2 = QtWidgets.QListWidget(self.groupBox_4)
        self.listWidget_2.setObjectName("listWidget_2")
        self.gridLayout_14.addWidget(self.listWidget_2, 1, 0, 3, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_4)
        icon = QtGui.QIcon.fromTheme("list-add")
        self.pushButton_3.setIcon(icon)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_14.addWidget(self.pushButton_3, 1, 1, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_4)
        icon = QtGui.QIcon.fromTheme("list-remove")
        self.pushButton_4.setIcon(icon)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_14.addWidget(self.pushButton_4, 2, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_14.addItem(spacerItem6, 3, 1, 1, 1)
        self.gridLayout_16.addWidget(self.groupBox_4, 2, 0, 1, 3)
        self.groupBox_5 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_5.setCheckable(True)
        self.groupBox_5.setChecked(False)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.lineEdit_14 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.gridLayout_15.addWidget(self.lineEdit_14, 0, 0, 1, 2)
        self.listWidget_3 = QtWidgets.QListWidget(self.groupBox_5)
        self.listWidget_3.setObjectName("listWidget_3")
        self.gridLayout_15.addWidget(self.listWidget_3, 1, 0, 3, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox_5)
        icon = QtGui.QIcon.fromTheme("list-add")
        self.pushButton_5.setIcon(icon)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_15.addWidget(self.pushButton_5, 1, 1, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.groupBox_5)
        icon = QtGui.QIcon.fromTheme("list-remove")
        self.pushButton_6.setIcon(icon)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout_15.addWidget(self.pushButton_6, 2, 1, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_15.addItem(spacerItem7, 3, 1, 1, 1)
        self.gridLayout_16.addWidget(self.groupBox_5, 3, 0, 1, 3)
        spacerItem8 = QtWidgets.QSpacerItem(416, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_16.addItem(spacerItem8, 0, 2, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_12.addWidget(self.scrollArea, 0, 0, 1, 1)
        Wizard.addPage(self.wizardPage_5)
        self.wizardPage_6 = QtWidgets.QWizardPage()
        self.wizardPage_6.setObjectName("wizardPage_6")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.wizardPage_6)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.checkBox_2 = QtWidgets.QCheckBox(self.wizardPage_6)
        self.checkBox_2.setChecked(True)
        self.checkBox_2.setObjectName("checkBox_2")
        self.gridLayout_19.addWidget(self.checkBox_2, 0, 0, 1, 1)
        self.checkBox_3 = QtWidgets.QCheckBox(self.wizardPage_6)
        self.checkBox_3.setChecked(False)
        self.checkBox_3.setTristate(False)
        self.checkBox_3.setObjectName("checkBox_3")
        self.gridLayout_19.addWidget(self.checkBox_3, 1, 0, 1, 1)
        self.checkBox_4 = QtWidgets.QCheckBox(self.wizardPage_6)
        self.checkBox_4.setChecked(True)
        self.checkBox_4.setTristate(False)
        self.checkBox_4.setObjectName("checkBox_4")
        self.gridLayout_19.addWidget(self.checkBox_4, 2, 0, 1, 1)
        self.checkBox_5 = QtWidgets.QCheckBox(self.wizardPage_6)
        self.checkBox_5.setChecked(True)
        self.checkBox_5.setObjectName("checkBox_5")
        self.gridLayout_19.addWidget(self.checkBox_5, 3, 0, 1, 1)
        self.checkBox_6 = QtWidgets.QCheckBox(self.wizardPage_6)
        self.checkBox_6.setObjectName("checkBox_6")
        self.gridLayout_19.addWidget(self.checkBox_6, 4, 0, 1, 1)
        self.checkBox_7 = QtWidgets.QCheckBox(self.wizardPage_6)
        self.checkBox_7.setChecked(True)
        self.checkBox_7.setObjectName("checkBox_7")
        self.gridLayout_19.addWidget(self.checkBox_7, 5, 0, 1, 1)
        self.checkBox_8 = QtWidgets.QCheckBox(self.wizardPage_6)
        self.checkBox_8.setChecked(True)
        self.checkBox_8.setObjectName("checkBox_8")
        self.gridLayout_19.addWidget(self.checkBox_8, 6, 0, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(20, 239, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_19.addItem(spacerItem9, 7, 0, 1, 1)
        Wizard.addPage(self.wizardPage_6)

        self.retranslateUi(Wizard)
        self.tabWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(Wizard)

    def retranslateUi(self, Wizard):
        _translate = QtCore.QCoreApplication.translate
        Wizard.setWindowTitle(_translate("Wizard", "Wizard"))
        self.wizardPage.setTitle(_translate("Wizard", "RPM package creation"))
        self.wizardPage.setSubTitle(_translate("Wizard", "Metadata"))
        self.label_2.setText(_translate("Wizard", "Package name:"))
        self.label_3.setText(_translate("Wizard", "Release:"))
        self.lineEdit_2.setText(_translate("Wizard", "1%{?dist}"))
        self.label_4.setText(_translate("Wizard", "Summary:"))
        self.label_5.setText(_translate("Wizard", "Website:"))
        self.label_6.setText(_translate("Wizard", "License:"))
        self.lineEdit_5.setText(_translate("Wizard", "GPL-3"))
        self.label_7.setText(_translate("Wizard", "PC architecture:"))
        self.comboBox.setItemText(0, _translate("Wizard", "x86_64"))
        self.comboBox.setItemText(1, _translate("Wizard", "i386"))
        self.comboBox.setItemText(2, _translate("Wizard", "noarch"))
        self.groupBox.setTitle(_translate("Wizard", "Description"))
        self.wizardPage_2.setTitle(_translate("Wizard", "RPM package creation"))
        self.wizardPage_2.setSubTitle(_translate("Wizard", "License"))
        self.label_8.setText(_translate("Wizard", "Will save in /usr/share/doc/<Your program>/copyright"))
        self.plainTextEdit_2.setPlainText(_translate("Wizard", "<one line to give the program\'s name and a brief idea of what it does.>\n"
"    Copyright (C) <year>  <name of author>\n"
"\n"
"    This program is free software: you can redistribute it and/or modify\n"
"    it under the terms of the GNU General Public License as published by\n"
"    the Free Software Foundation, either version 3 of the License, or\n"
"    (at your option) any later version.\n"
"\n"
"    This program is distributed in the hope that it will be useful,\n"
"    but WITHOUT ANY WARRANTY; without even the implied warranty of\n"
"    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the\n"
"    GNU General Public License for more details.\n"
"\n"
"    You should have received a copy of the GNU General Public License\n"
"    along with this program.  If not, see <https://www.gnu.org/licenses/>."))
        self.wizardPage_3.setTitle(_translate("Wizard", "RPM package creation"))
        self.wizardPage_3.setSubTitle(_translate("Wizard", "Scripts"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Wizard", "Pre-Installation"))
        self.plainTextEdit_4.setPlainText(_translate("Wizard", "appstreamcli refresh-cache --force\n"
"update-mime-database /usr/share/mime"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Wizard", "Post-Installation"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Wizard", "Pre-Uninstall"))
        self.plainTextEdit_6.setPlainText(_translate("Wizard", "appstreamcli refresh-cache --force \n"
"update-mime-database /usr/share/mime"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Wizard", "Post-Uninstallation"))
        self.wizardPage2.setTitle(_translate("Wizard", "RPM package creation"))
        self.wizardPage2.setSubTitle(_translate("Wizard", "Dependencies"))
        self.commandLinkButton.setText(_translate("Wizard", "Add"))
        self.commandLinkButton_2.setText(_translate("Wizard", "Remove"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Wizard", "Package"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Wizard", "Version (blank - newest)"))
        self.wizardPage_4.setTitle(_translate("Wizard", "RPM package creation"))
        self.wizardPage_4.setSubTitle(_translate("Wizard", "New mime type"))
        self.groupBox_6.setTitle(_translate("Wizard", "Create new mime type"))
        self.label_11.setText(_translate("Wizard", "Name:"))
        self.lineEdit_8.setText(_translate("Wizard", "application/"))
        self.label_13.setText(_translate("Wizard", "Comment:"))
        self.label_14.setText(_translate("Wizard", "Pattern:"))
        self.lineEdit_10.setPlaceholderText(_translate("Wizard", "*.txt"))
        self.label_15.setText(_translate("Wizard", "Exec command:"))
        self.lineEdit_11.setPlaceholderText(_translate("Wizard", "myprogram --open %f"))
        self.wizardPage_5.setTitle(_translate("Wizard", "RPM package creation"))
        self.wizardPage_5.setSubTitle(_translate("Wizard", "Appstream"))
        self.label_12.setText(_translate("Wizard", "Categories:"))
        self.comboBox_2.setItemText(0, _translate("Wizard", "AudioVideo"))
        self.comboBox_2.setItemText(1, _translate("Wizard", "Audio"))
        self.comboBox_2.setItemText(2, _translate("Wizard", "Video"))
        self.comboBox_2.setItemText(3, _translate("Wizard", "Development"))
        self.comboBox_2.setItemText(4, _translate("Wizard", "Education"))
        self.comboBox_2.setItemText(5, _translate("Wizard", "Game"))
        self.comboBox_2.setItemText(6, _translate("Wizard", "Graphics"))
        self.comboBox_2.setItemText(7, _translate("Wizard", "Network"))
        self.comboBox_2.setItemText(8, _translate("Wizard", "Office"))
        self.comboBox_2.setItemText(9, _translate("Wizard", "Science"))
        self.comboBox_2.setItemText(10, _translate("Wizard", "Settings"))
        self.comboBox_2.setItemText(11, _translate("Wizard", "System"))
        self.comboBox_2.setItemText(12, _translate("Wizard", "Utility"))
        self.groupBox_3.setTitle(_translate("Wizard", "Keywords"))
        self.pushButton.setText(_translate("Wizard", "Add"))
        self.pushButton_2.setText(_translate("Wizard", "Delete"))
        self.groupBox_4.setTitle(_translate("Wizard", "Screenshots (URL or path)"))
        self.pushButton_3.setText(_translate("Wizard", "Add"))
        self.pushButton_4.setText(_translate("Wizard", "Delete"))
        self.groupBox_5.setTitle(_translate("Wizard", "Mimetypes"))
        self.pushButton_5.setText(_translate("Wizard", "Add"))
        self.pushButton_6.setText(_translate("Wizard", "Delete"))
        self.wizardPage_6.setTitle(_translate("Wizard", "RPM package creation"))
        self.wizardPage_6.setSubTitle(_translate("Wizard", "Last options"))
        self.checkBox_2.setText(_translate("Wizard", "Open-Source program"))
        self.checkBox_3.setText(_translate("Wizard", "Run program by terminal"))
        self.checkBox_4.setText(_translate("Wizard", "Delete tree after building"))
        self.checkBox_5.setText(_translate("Wizard", "Save RPM building settings for this project"))
        self.checkBox_6.setText(_translate("Wizard", "Install after build"))
        self.checkBox_7.setText(_translate("Wizard", "Build appstream"))
        self.checkBox_8.setText(_translate("Wizard", "Build menu launcher"))
